name: ci-pipeline
on:
  push:
    branches:
      - karsajobs
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint

      - name: Run Hadolint on Dockerfile
        run: hadolint Dockerfile

  test-app:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.15" # Sesuaikan versi Go jika diperlukan

      - name: Get dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run build and push script
        run: bash build_push_image_karsajobs.sh
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
